version: '3.9'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.97.0
    command: ['--config=/etc/otelcol/config.yaml']
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - '4318:4318'   # OTLP HTTP
      - '8889:8889'   # Prometheus exporter

  prometheus:
    image: prom/prometheus:v2.51.2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:10.4.2
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - '3005:3000'
    depends_on:
      - prometheus
